### ISSUE TITLE
Add Sequelize as an ORM for the MySQL Database

### ISSUE THREAD

**Issue by Julien-Broyard** [IdekaPlatform/ideka-back#6]
I propose to add Sequelize as an ORM for the MySQL database. It is safer to use an ORM to avoid SQL injections into our code and it makes the code easier to maintain.

Sequelize is a promise-based ORM for Node.js v4 and up. It supports the dialects PostgreSQL, MySQL, SQLite and MSSQL and features solid transaction support, relations, read replication and more.

Here is the [link](http://docs.sequelizejs.com/) to the official docs

**Comment by SirHaswell** [comment]
I am in favour of the transition with this ORM the reasons given were legitimate
