### ISSUE TITLE
Add ESLint + Prettier + Husky to enforce a code style for the whole team

### ISSUE THREAD

**Issue by Julien-Broyard** [IdekaPlatform/ideka-back#7]
I think that by adding ESLint, Prettier, Husky we can enforce a code style for the whole team. 
Like this the code will be more easily maintained, and the code will be much easier to read.

[ESLint](https://eslint.org/)
[Prettier](https://prettier.io/)
[Husky](https://github.com/typicode/husky)

**Comment by SirHaswell** [comment]
Yes you can use this ;)
